### ISSUE TITLE
Losse tabellen

### ISSUE THREAD

**Issue by dhvenema** [BROprogramma/SAMPLE#3]
[SAMPLE-cat.html#L4081](https://github.com/BROprogramma/SAMPLE/blob/gh-pages/data/SAMPLE-cat.html#L4081) en [SAMPLE-cat.html#L4126](https://github.com/BROprogramma/SAMPLE/blob/gh-pages/data/SAMPLE-cat.html#L4126) geven twee lossen tabellen aan in "Enumeration details BrickSize" en "Enumeration details Status". Terwijl in, in beide gevallen, dit één tabel zou moeten zijn. Zie hieronder een voorbeeld van hoe ik verwacht dat het in de code zou staan.

```html
<section id="detail_d6514e1281" class="notoc">
  <h3>Enumeration details <a href="#"></a>Status</h3>

  <table>
    <colgroup width="10%"></colgroup>
    <colgroup width="30%"></colgroup>
    <colgroup width="60%"></colgroup>
    <thead>
      <tr>
        <th colspan="2">Definition</th>
        <th>Status of brick production</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th>Code</th>
        <th>Name</th>
        <th>Definition</th>
      </tr>
      <tr>
        <td></td>
        <td>in-progress</td>
        <td>The task or process is not yet in production</td>
      </tr>
      <tr>
        <td></td>
        <td>in-production</td>
        <td>The task or process is in production</td>
      </tr>
    </tbody>
  </table>
</section>
```

**Comment by ArjanLoeffen** [comment]
gedaan, zie https://broprogramma.github.io/SAMPLE
